spring.application.name=sistema-restaurante-api
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/restaurante}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:restaurante}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:restaurante}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
server.port=8080
